In [2]:
import numpy as np
import sympy as sm

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [4]:
a.dot(b)

32

In [5]:
a @ b

32

In [6]:
a @ 2

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [7]:
a @ a

14

In [8]:
a.dot(2)

array([2, 4, 6])

In [9]:
def f(x):
    return x ** 2

In [10]:
g = np.array([[1.], [2.]])
p = np.array([[3.], [4.]])

In [11]:
g @ p

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [12]:
g.dot(p)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [13]:
g.dot(p.transpose())

array([[3., 4.],
       [6., 8.]])

In [14]:
g.transpose().dot(p)

array([[11.]])

In [15]:
a @ b

32

In [16]:
a @ b.transpose()

32

In [17]:
a @ np.atleast_2d(b).transpose()

array([32])

In [18]:
a.dot(np.atleast_2d(b))

ValueError: shapes (3,) and (1,3) not aligned: 3 (dim 0) != 1 (dim 0)

In [19]:
a.dot(np.atleast_2d(b).transpose())

array([32])

In [20]:
np.atleast_2d(a).dot(b)

array([32])

In [21]:
np.atleast_2d(a).transpose().dot(b)

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [22]:
np.atleast_2d(a).dot(np.atleast_2d(b))

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [ ]:
np.atleast_2d(a).dot(np.atleast_2d(b).transpose())

In [23]:
np.atleast_2d(a).transpose().dot(np.atleast_2d(b))

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [24]:
np.atleast_2d(a).dot(b)

array([32])

In [25]:
np.atleast_2d(a).transpose().dot(b)

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [26]:
t = np.atleast_2d(a)

In [27]:
t.transpose()

array([[1],
       [2],
       [3]])

In [28]:
from sympy.abc import x, y
sm.solve(sm.simplify(f(x) + y), y)

[-x**2]

In [29]:
t = np.exp(x) + y
t
sm.solve(sm.simplify(t), y)

TypeError: loop of ufunc does not support argument 0 of type Symbol which has no callable exp method

In [ ]:
sm.diff(sm.simplify(f(x) + y), x)

In [ ]:
arr = np.array([1., 2., 3., 4., 5.])

In [ ]:
arr[0:3]

In [30]:
matrix = np.eye(5)

In [31]:
len(matrix)

5

In [32]:
matrix = np.shape((2, 3))

In [33]:
len(matrix)

1

In [35]:
matrix = np.array([[1, 2, 3], [1, 2, 3]])

In [36]:
len(matrix)

2