In [2]:
import numpy as np
import sympy as sm

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [4]:
a.dot(b)

32

In [5]:
a @ b

32

In [6]:
a @ 2

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
a @ a

In [ ]:
a.dot(2)

In [ ]:
def f(x):
    return x ** 2

In [7]:
g = np.array([[1.], [2.]])
p = np.array([[3.], [4.]])

In [8]:
g @ p

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [9]:
g.dot(p)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [10]:
g.dot(p.transpose())

array([[3., 4.],
       [6., 8.]])

In [11]:
g.transpose().dot(p)

array([[11.]])

In [12]:
a @ b

32

In [13]:
a @ b.transpose()

32

In [14]:
a @ np.atleast_2d(b).transpose()

array([32])

In [15]:
a.dot(np.atleast_2d(b))

ValueError: shapes (3,) and (1,3) not aligned: 3 (dim 0) != 1 (dim 0)

In [16]:
a.dot(np.atleast_2d(b).transpose())

array([32])

In [17]:
np.atleast_2d(a).dot(b)

array([32])

In [18]:
np.atleast_2d(a).transpose().dot(b)

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [19]:
np.atleast_2d(a).dot(np.atleast_2d(b))

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [20]:
np.atleast_2d(a).dot(np.atleast_2d(b).transpose())

array([[32]])

In [21]:
np.atleast_2d(a).transpose().dot(np.atleast_2d(b))

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [22]:
np.atleast_2d(a).dot(b)

array([32])

In [23]:
np.atleast_2d(a).transpose().dot(b)

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [ ]:
t = np.atleast_2d(a)

In [24]:
t.transpose()

NameError: name 't' is not defined

In [25]:
from sympy.abc import x, y
sm.solve(sm.simplify(f(x) + y), y)

NameError: name 'f' is not defined

In [ ]:
t = np.exp(x) + y
t
sm.solve(sm.simplify(t), y)

In [26]:
sm.diff(sm.simplify(f(x) + y), x)

NameError: name 'f' is not defined

In [27]:
arr = np.array([1., 2., 3., 4., 5.])

In [28]:
arr[0:3]

array([1., 2., 3.])

In [29]:
matrix = np.eye(5)

In [30]:
len(matrix)

5

In [31]:
matrix = np.shape((2, 3))

In [32]:
len(matrix)

1

In [33]:
matrix = np.array([[1, 2, 3], [1, 2, 3]])

In [34]:
len(matrix)

2

In [35]:
np.exp(10)

22026.465794806718

In [36]:
np.sqrt([1, 2, 3])

array([1.        , 1.41421356, 1.73205081])

In [37]:
x = (np.array([1, 2, 3]))

In [38]:
x

array([1, 2, 3])

In [39]:
x ** 2

array([1, 4, 9])

In [40]:
x

array([1, 2, 3])

In [41]:
np.dot(np.array([1, 1, 1]), np.array([2, 2]))

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)