In [42]:
import numpy as np
import sympy as sm

In [43]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [44]:
a.dot(b)

32

In [45]:
a @ b

32

In [46]:
a @ 2

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
a @ a

In [ ]:
a.dot(2)

In [ ]:
def f(x):
    return x ** 2

In [63]:
g = np.array([[1.], [2.]])
p = np.array([[3.], [4.]])

In [64]:
g @ p

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [65]:
g.dot(p)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [66]:
g.dot(p.transpose())

array([[3., 4.],
       [6., 8.]])

In [67]:
g.transpose().dot(p)

array([[11.]])

In [68]:
a @ b

32

In [69]:
a @ b.transpose()

32

In [70]:
a @ np.atleast_2d(b).transpose()

array([32])

In [71]:
a.dot(np.atleast_2d(b))

ValueError: shapes (3,) and (1,3) not aligned: 3 (dim 0) != 1 (dim 0)

In [72]:
a.dot(np.atleast_2d(b).transpose())

array([32])

In [73]:
np.atleast_2d(a).dot(b)

array([32])

In [74]:
np.atleast_2d(a).transpose().dot(b)

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [75]:
np.atleast_2d(a).dot(np.atleast_2d(b))

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [76]:
np.atleast_2d(a).dot(np.atleast_2d(b).transpose())

array([[32]])

In [77]:
np.atleast_2d(a).transpose().dot(np.atleast_2d(b))

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [78]:
np.atleast_2d(a).dot(b)

array([32])

In [79]:
np.atleast_2d(a).transpose().dot(b)

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [84]:
t = np.atleast_2d(a)

In [85]:
t.transpose()

array([[1],
       [2],
       [3]])

In [90]:
from sympy.abc import x, y
sm.solve(sm.simplify(f(x) + y), y)

[-x**2]

In [95]:
sm.solve(sm.simplify(np.exp(x) + y), y)

TypeError: loop of ufunc does not support argument 0 of type Symbol which has no callable exp method